Algoritmo "CalculoDeMedia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Max
// Descrição   : Calculo de Média Aritmetica
// Autor(a)    : Edson Junior
// Data atual  : 02/09/2025
Var
n1, n2, n3: real
m:real

Inicio
Escreval("**Calculo de Média**")

Escreva("Digite a primeira nota: ")
leia(n1)

Escreva("Digite a segunda nota: ")
leia(n2)

Escreva("Digite a terceira nota: ")
leia(n3)

m := (n1 + n2 + n3) / 3

Escreva("A média do Aluno(a) é: ",m)

Fimalgoritmo