Algoritmo "ConversorTemperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Max
// Descrição   : Conversor de Temperatura
// Autor(a)    : Edson Junior
// Data atual  : 02/09/2025
Var
C, F: real


Inicio
escreval("--Conversor de Temperatura--")
escreva("Digite a temperatura em Celsius: ")
leia(C)
F <- C * 1.8 + 32

escreval("A temperatura em Fahrenheit é: ",F)

Fimalgoritmo