Algoritmo "ParOuImpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Max
// Descrição   : Calculo de Par ou Impar
// Autor(a)    : Edson Junior
// Data atual  : 02/09/2025
Var
n1: inteiro


Inicio
escreval("*Par ou Impar*")
escreva("Digite um número: ")
leia(n1)

SE n1 mod 2 = 0 entao
escreval("O número", n1, " é par.")
senao
escreval("O número", n1, " é impar.")
fimse

Fimalgoritmo